version: '3.8'
services:
  nginx:
    build: ./
    depends_on:
      - certbot
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl
      - ./nginx/website:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    restart: always
