name: Build, Push and Deploy Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push nginx Docker image
      run: |
        docker buildx build --push \
        --tag ilunoi/rpf.banking.nginx:latest \
        -f ./rpfbank.pp.ua/Dockerfile ./rpfbank.pp.ua


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ilunoi/rpf.banking.nginx:latest
          docker stop rpfbanking-nginx || true
          docker rm rpfbanking-nginx || true
          docker run -d --name rpfbanking-nginx -p 13:22 -p 443:443 ilunoi/rpf.banking.nginx:latest

  owasp:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Start OWASP ZAP Baseline Scan
        run: |
          chmod -R 777 $(pwd)
          docker pull ictu/zap2docker-weekly
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t https://rpfbank.pp.ua -r /zap/wrk/zap-report.html
      - name: Copy OWASP ZAP report to repository folder
        run: |
          mkdir -p report_OWASP
          cp zap-report.html report_OWASP/

      - name: Commit and push OWASP ZAP report to repository
        run: |
          git config --global user.name "GitHub Actions"
          git add report_OWASP/zap-report.html
          git commit -m "Add OWASP ZAP report"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
