name: Build, Push and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push certbot Docker image
      run: |
        docker buildx build --push \
          --tag ilunoi/rpf.banking.certbot:latest \
          -f ./rpfbank.pp.ua/certbot/Dockerfile ./rpfbank.pp.ua
    
    - name: Build and push nginx Docker image
      run: |
        docker buildx build --push \
          --tag ilunoi/rpf.banking.nginx:latest \
          -f ./rpfbank.pp.ua/Dockerfile ./rpfbank.pp.ua
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ilunoi/rpf.banking.certbot:latest
          docker pull ilunoi/rpf.banking.nginx:latest
          docker stop rpfbanking-certbot || true
          docker stop rpfbanking-nginx || true
          docker rm rpfbanking-certbot || true
          docker rm rpfbanking-nginx || true
          docker run -d --name rpfbanking-certbot ilunoi/rpf.banking.certbot:latest
          docker run -d --name rpfbanking-nginx ilunoi/rpf.banking.nginx:latest
