name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image  
      run: |
        docker compose -f ./rpfbank.pp.ua/docker-compose.yml build 

    - name: Start Docker Compose services
      run: |
        yes 1 | docker compose -f ./rpfbank.pp.ua/docker-compose.yml run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ --non-interactive --agree-tos -d rpfbank.pp.ua
        docker compose -f ./rpfbank.pp.ua/docker-compose.yml up -d -t ilunoi/rpf.banking.project:v0.0.1
        
    - name: Login to Docker Hub  
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker
      working-directory: ./rpfbank.pp.ua/
      run: |
        docker push ilunoi/rpf.banking.project:v0.0.1

    - name: Stop and remove Docker Compose services
      run: |
        docker compose -f ./rpfbank.pp.ua/docker-compose.yml down
