name: Build, Push and Deploy Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push nginx Docker image
      run: |
        docker buildx build --push \
        --tag ilunoi/rpf.banking.nginx:latest \
        -f ./rpfbank.pp.ua/Dockerfile ./rpfbank.pp.ua


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ilunoi/rpf.banking.nginx:latest
          docker stop rpfbanking-nginx || true
          docker rm rpfbanking-nginx || true
          docker run -d --name rpfbanking-nginx -p 13:22 -p 443:443 ilunoi/rpf.banking.nginx:latest

  owasp:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Start OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ictu/zap2docker-weekly'
          target: 'https://rpfbank.pp.ua'
          cmd_options: '-a'
          rules_file_name: 'report_OWASP/zap-report.html'
      - name: Check files in the workspace
        run: ls -R ./report_OWASP/
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ZAP-Report
          overwrite: true
          path: ./report_OWASP/zap-report.txt
