name: Build, Push and Deploy Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push nginx Docker image
      run: |
        docker buildx build --push \
        --tag ilunoi/rpf.banking.nginx:latest \
        -f ./rpfbank.pp.ua/Dockerfile ./rpfbank.pp.ua


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ilunoi/rpf.banking.nginx:latest
          docker stop rpfbanking-nginx || true
          docker rm rpfbanking-nginx || true
          docker run -d --name rpfbanking-nginx -p 13:22 -p 443:443 ilunoi/rpf.banking.nginx:latest

  owasp:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: mkdir -p report_OWASP
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_issue_writing: true
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://rpfbank.pp.ua'
          cmd_options: '-a'
          artifact_name: zap_scan
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: zap_scan
          path: report_OWASP
